### ISSUE TITLE
Permission denied for camera causes application to crash when taking photo in edit profile photo

### ISSUE THREAD

**Issue by MarcusBoay** [CMPUT301W19T11/Atheneum#126]
Taking a photo for the user's profile when camera permissions are denied for the application crashes the application.

1. Have camera permission denied for the application in the app. settings.
2. Go to profile.
3. Edit profile and take a photo.
4. Application crashes.

The application should ask for camera permissions and not crash the application.

**Comment by ishchow** [comment]
I tried to run the camera stuff again today and I noticed this was still broken on my Huawei Nova Plus.

Same steps to reproduce. Except the stacktrace looks different.

```
2019-03-17 00:02:59.434 15949-15949/com.example.atheneum E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.atheneum, PID: 15949
    java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE cmp=com.huawei.camera/.ThirdCamera } from ProcessRecord{e6b5530 15949:com.example.atheneum/u0a213} (pid=15949, uid=10213) with revoked permission android.permission.CAMERA
        at android.os.Parcel.readException(Parcel.java:1665)
        at android.os.Parcel.readException(Parcel.java:1618)
        at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3097)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1539)
        at android.app.Activity.startActivityForResult(Activity.java:4391)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
        at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:886)
        at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:995)
        at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:1103)
        at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:1092)
        at com.example.atheneum.controllers.PictureController.dispatchTakePictureIntent(PictureController.java:91)
        at com.example.atheneum.fragments.EditProfileFragment$ProfilePictureOnClickListener.onClick(EditProfileFragment.java:76)
        at android.view.View.performClick(View.java:5646)
        at android.view.View$PerformClick.run(View.java:22473)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

Going to try some of the stuff here to fix this: Android: Permission Denial: starting Intent with revoked permission android.permission.CAMERA.
