### ISSUE TITLE
ProfilePic in MainActivity NullPointerException

### ISSUE THREAD

**Issue by MarcusBoay** [CMPUT301W19T11/Atheneum#152]
I logged in and out of multiple accounts and the application crash. I was on the master branch.

**To Reproduce**
I'm not entirely sure how to reproduce the bug. I logged in and out of multiple accounts and the application just crashed.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.atheneum, PID: 5649
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setImageBitmap(android.graphics.Bitmap)' on a null object reference
        at com.example.atheneum.activities.MainActivity$1.onChanged(MainActivity.java:113)
        at com.example.atheneum.activities.MainActivity$1.onChanged(MainActivity.java:102)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at android.arch.lifecycle.Transformations$1.onChanged(Transformations.java:70)
        at android.arch.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at com.example.atheneum.utils.FirebaseQueryLiveData.access$400(FirebaseQueryLiveData.java:20)
        at com.example.atheneum.utils.FirebaseQueryLiveData$MyValueEventListener.onDataChange(FirebaseQueryLiveData.java:126)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(com.google.firebase:firebase-database@@16.0.6:75)
        at com.google.firebase.database.core.view.DataEvent.fire(com.google.firebase:firebase-database@@16.0.6:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@16.0.6:55)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6111)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

This bug may be related to requesting a book.

**Comment by ishchow** [comment]
Also haven't seen this since #189 was merged.

**Comment by MarcusBoay** [comment]
This may have been fixed
