### ISSUE TITLE
Crash while on borrower page when other user accepts request

### ISSUE THREAD

**Issue by MarcusBoay** [CMPUT301W19T11/Atheneum#158]
I made a request for a book previously and was on the borrower page. When the request was accepted by the owner, the application crashed.

**To Reproduce**
1. Make a request on a book and stay on the borrower page fragment.
2. Have the owner accept the request.
3. Crash

**Expected behavior**
Shouldn't happen.

**Stack Trace**
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.atheneum, PID: 15086
    java.lang.IllegalStateException: Fragment BorrowerPageFragment{11bd535} not attached to a context.
        at android.support.v4.app.Fragment.requireContext(Fragment.java:696)
        at android.support.v4.app.Fragment.getResources(Fragment.java:760)
        at android.support.v4.app.Fragment.getString(Fragment.java:782)
        at com.example.atheneum.fragments.BorrowerPageFragment$4.onDataChange(BorrowerPageFragment.java:198)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(com.google.firebase:firebase-database@@16.0.6:75)
        at com.google.firebase.database.core.view.DataEvent.fire(com.google.firebase:firebase-database@@16.0.6:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@16.0.6:55)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6111)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

This could be because of the ValueEventListener listening for onDataChange.

**Additional Context**
We were on the current master branch.

**Comment by ishchow** [comment]
I think this was a problem with trying to accept a book that already has a borrower, doesn't seem related to the UI of the borrower page.
