### ISSUE TITLE
Requesting a book crashes the app sometimes

### ISSUE THREAD

**Issue by MarcusBoay** [CMPUT301W19T11/Atheneum#183]
Requesting a book crashes the app sometimes.

**To Reproduce**
1. Go to Borrower from Home page
2. Hit '+' FAB
3. Request any book
4. You may need to do this multiple times
Stack trace:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.atheneum, PID: 28547
    java.lang.IllegalStateException: Fragment BorrowerPageFragment{2743c11} not attached to a context.
        at android.support.v4.app.Fragment.requireContext(Fragment.java:696)
        at android.support.v4.app.Fragment.getResources(Fragment.java:760)
        at android.support.v4.app.Fragment.getString(Fragment.java:782)
        at com.example.atheneum.fragments.BorrowerPageFragment$4.onDataChange(BorrowerPageFragment.java:201)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(com.google.firebase:firebase-database@@16.0.6:75)
        at com.google.firebase.database.core.view.DataEvent.fire(com.google.firebase:firebase-database@@16.0.6:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@16.0.6:55)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6111)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

I think this is due to the some lifecycle thing related to one of the borrower pages.

**Comment by ishchow** [comment]
I haven't seen this since #189 was merged. I think it should be closed. What do you think @MarcusBoay?

**Comment by MarcusBoay** [comment]
This may have been fixed
