### ISSUE TITLE
App Crashes after Borrower Makes a Request Sometimes

### ISSUE THREAD

**Issue by ishchow** [CMPUT301W19T11/Atheneum#195]
**Describe the bug**

**To Reproduce**
1. Attempt to request a book
2. Click request button
3. App crashes

**Expected behavior**
After the request has been made, the request activity should be finished not crash and then go to main.

**Stack Trace**
```
2019-03-30 14:06:58.892 26533-26533/com.example.atheneum E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.atheneum, PID: 26533
    java.lang.IllegalStateException: Fragment BorrowerRequestsFragment{9516a8d} not attached to a context.
        at android.support.v4.app.Fragment.requireContext(Fragment.java:696)
        at android.support.v4.app.Fragment.getResources(Fragment.java:760)
        at android.support.v4.app.Fragment.getString(Fragment.java:782)
        at com.example.atheneum.fragments.BorrowerRequestsFragment$4.onDataChange(BorrowerRequestsFragment.java:207)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(com.google.firebase:firebase-database@@16.0.6:75)
        at com.google.firebase.database.core.view.DataEvent.fire(com.google.firebase:firebase-database@@16.0.6:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@16.0.6:55)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
2019-03-30 14:06:58.897 1856-5468/? E/ReportTools: This is not beta user build
```

**Smartphone (please complete the following information):**
 - Huawei Nova Plus

**Additional context**
The request lifecycle flow is very strange. I press back and end up in book's i've already requested when trying to search for new books to request.

**Comment by Kaho-Lee** [comment]
I also found this error happening very often after fixing the crash in accepting a request in owner fragment.

The search would go back to its own activity after pressing the back button. After a new request is made,  the app would go back to the activity with book search.

And I have make some change of thee life cycle in my new PR. The number of error occurring decreases significantly. But I believed the bug still exist. If you find again, please report in this issues.

**Comment by Kaho-Lee** [comment]
I have change the data listening method in the error in borrower fragment.

I have not got the same error for a period in my phone Moto E5 Play

**Comment by ishchow** [comment]
I haven't seen this since #189 was merged so I'm going to close this.
