### ISSUE TITLE
App crash after making a new request happening from BorrowerRequestListAdapter

### ISSUE THREAD

**Issue by Kaho-Lee** [CMPUT301W19T11/Atheneum#212]
**Describe the bug**
App Crash after making a new request happening from BorrowerRequestListAdapter
Is any one find the similar error when using the app?

**To Reproduce**
1. Go to BorrowerRequestFragment
2. Click on 'floating button'
3. Scroll down to 'a available/requested book and make a request'

**Expected behavior**
Go back to NewRequestActivity

**Smartphone (please complete the following information):**
 - Device:  Android Studio Emulator, Pixel API28

**Additional context**
2019-04-01 11:59:39.087 28188-28258/com.example.atheneum E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.example.atheneum, PID: 28188
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.example.atheneum.views.adapters.BorrowerRequestListAdapter$1.areItemsTheSame(BorrowerRequestListAdapter.java:36)
        at com.example.atheneum.views.adapters.BorrowerRequestListAdapter$1.areItemsTheSame(BorrowerRequestListAdapter.java:33)
        at android.support.v7.recyclerview.extensions.AsyncListDiffer$1$1.areItemsTheSame(AsyncListDiffer.java:262)
        at android.support.v7.util.DiffUtil.diffPartial(DiffUtil.java:233)
        at android.support.v7.util.DiffUtil.calculateDiff(DiffUtil.java:145)
        at android.support.v7.util.DiffUtil.calculateDiff(DiffUtil.java:105)
        at android.support.v7.recyclerview.extensions.AsyncListDiffer$1.run(AsyncListDiffer.java:246)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by AY-Chen** [comment]
This is an account related problem, not universal. Closing issue.
