### ISSUE TITLE
Profile View Error

### ISSUE THREAD

**Issue by ishchow** [CMPUT301W19T11/Atheneum#68]
I think this is somehow related to #64 

I find that I can't view the profile of the current user when I click on it before I ever search on a user in the database.

Steps to reproduce:
1. Logout of session
2. Sign in
3. Immediately click view profile

Result:
Instead of viewing the current user profile, some kind of runtime error occurs and the app goes back to the home fragment after re-rendering the main activity.

One interesting thing to note here is that if instead of executing step 3, if you instead search for a user before you click the View Profile tab in the nav bar either your user profile will be shown properly or I run into issue #64

**Comment by ishchow** [comment]
By following the steps to reproduce I find this happens:

```
2019-03-04 22:28:34.429 13448-13448/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.atheneum, PID: 13448
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.atheneum/com.example.atheneum.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.example.atheneum.models.User.getUserName()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.example.atheneum.models.User.getUserName()' on a null object reference
        at com.example.atheneum.fragments.ViewProfileFragment.onCreateView(ViewProfileFragment.java:74)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1254)
        at android.app.Activity.performStart(Activity.java:6935)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2756)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
```
