### ISSUE TITLE
AddBookActivity hits runtime error

### ISSUE THREAD

**Issue by ishchow** [CMPUT301W19T11/Atheneum#69]
Steps to reproduce:
1. Log in
2. Click "Add New Book" on navbar

Result:
App crashes and returns to main activity with the following stack trace:

```
2019-03-04 23:17:48.010 1843-16303/? E/PF_API_NATIVE: check perfhub service fail! 
2019-03-04 23:17:48.013 17608-17608/com.example.atheneum E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.atheneum, PID: 17608
    android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.atheneum/com.example.atheneum.activities.AddBookActivity}; have you declared this activity in your AndroidManifest.xml?
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1850)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1544)
        at android.app.Activity.startActivityForResult(Activity.java:4391)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at android.app.Activity.startActivityForResult(Activity.java:4335)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
        at android.app.Activity.startActivity(Activity.java:4702)
        at android.app.Activity.startActivity(Activity.java:4670)
        at com.example.atheneum.activities.MainActivity.onNavigationItemSelected(MainActivity.java:159)
        at android.support.design.widget.NavigationView$1.onMenuItemSelected(NavigationView.java:170)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at android.support.design.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:352)
        at android.view.View.performClick(View.java:5646)
        at android.view.View$PerformClick.run(View.java:22473)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
2019-03-04 23:17:48.025 1843-5958/? E/ReportTools: This is not beta user build
```

**Comment by ishchow** [comment]
Yes

**Comment by siyuamymi** [comment]
Hmm, this is weird, I haven't been able to recreate the error.

**Comment by ishchow** [comment]
I haven't run into this anymore either. I remember when I saw it that I logged out and logged in and it was working again. Maybe it's a problem with the auth credentials. I'm closing this.
